DROP TABLE IF EXISTS EXAMPLE;

CREATE TABLE News (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  text VARCHAR(300) NOT NULL,
  title VARCHAR(30) NOT NULL,
  data VARCHAR(30) NOT NULL
);

CREATE TABLE Comment (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NewsId VARCHAR(30) NOT NULL,
  comment VARCHAR(300) NOT NULL,
  author VARCHAR(30) NOT NULL,
  data VARCHAR(30) NOT NULL

);

